package com.example.md3.data.model.commissioning


import com.google.gson.annotations.SerializedName

data class CustomFieldX(
    @SerializedName("auto_generated_number")
    val autoGeneratedNumber: Any,
    @SerializedName("data_type")
    val dataType: String,
    @SerializedName("dropdown_options")
    val dropdownOptions: Any,
    @SerializedName("flag_mandatory")
    val flagMandatory: Boolean,
    @SerializedName("flag_show_in_pdf")
    val flagShowInPdf: Boolean,
    @SerializedName("help_text")
    val helpText: String,
    @SerializedName("id")
    val id: String,
    @SerializedName("label_name")
    val labelName: String,
    @SerializedName("module")
    val module: String
)