package com.asap.codenicely.pdf.gstinvoicing.free.mobile.easy.gst.invoice.quick.quickinvoice.gstinvoicing.ui.custom_fields.adapters

import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListAdapter
import androidx.recyclerview.widget.RecyclerView
import com.asap.codenicely.pdf.gstinvoicing.free.mobile.easy.gst.invoice.quick.quickinvoice.gstinvoicing.ui.custom_fields.adapters.viewholder.CheckboxCustomFieldViewHolder
import com.asap.codenicely.pdf.gstinvoicing.free.mobile.easy.gst.invoice.quick.quickinvoice.gstinvoicing.ui.custom_fields.adapters.viewholder.DateCustomFieldViewHolder
import com.asap.codenicely.pdf.gstinvoicing.free.mobile.easy.gst.invoice.quick.quickinvoice.gstinvoicing.ui.custom_fields.adapters.viewholder.DropdownCustomFieldViewHolder
import com.asap.codenicely.pdf.gstinvoicing.free.mobile.easy.gst.invoice.quick.quickinvoice.gstinvoicing.ui.custom_fields.adapters.viewholder.TextViewCustomFieldViewHolder
import com.example.md3.R
import com.example.md3.data.model.checksheet.Field
import com.example.md3.databinding.CheckboxCustomFieldBinding
import com.example.md3.databinding.DateCustomFieldBinding
import com.example.md3.databinding.DropdownCustomFieldBinding
import com.example.md3.databinding.SingleLineTextCustomFieldBinding


class CustomFieldsAdapter(var  isDisabled : Boolean) : ListAdapter<Field, RecyclerView.ViewHolder>(COMPARATOR) {

    override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
        val item = getItem(position)
        when(holder){
            is TextViewCustomFieldViewHolder -> {
                holder.bind(item)
            }
//            is NumberCustomFieldViewHolder -> {
//                holder.bind(item)
//                holder.binding.transporterIdText.setCompoundDrawablesRelativeWithIntrinsicBounds(
//                    KotlinConstant.getCustomFieldsDrawableResource(item.dataType!!),
//                    0,
//                    0,
//                    0
//                )
//            }
//            is DecimalCustomFieldViewHolder -> {
//                holder.bind(item)
//                holder.binding.transporterIdText.setCompoundDrawablesRelativeWithIntrinsicBounds(
//                    KotlinConstant.getCustomFieldsDrawableResource(item.dataType!!),
//                    0,
//                    0,
//                    0
//                )
//            }
            is CheckboxCustomFieldViewHolder -> {
                holder.bind(item)
            }
            is DateCustomFieldViewHolder -> {
                holder.bind(item)
            }
//            is DateAndTimeCustomFieldViewHolder -> {
//                holder.bind(item)
//            }
//            is AutoGeneratedNumberCustomFieldViewHolder -> {
//                holder.bind(item)
//                holder.binding.transporterIdText.setCompoundDrawablesRelativeWithIntrinsicBounds(
//                    KotlinConstant.getCustomFieldsDrawableResource(item.dataType!!),
//                    0,
//                    0,
//                    0
//                )
//            }
            is DropdownCustomFieldViewHolder -> {
                holder.bind(item)
            }
//            is MultiSelectCustomFieldViewHolder -> {
//                holder.bind(item)
//                holder.binding.autoCompleteTextView.setCompoundDrawablesRelativeWithIntrinsicBounds(
//                    KotlinConstant.getCustomFieldsDrawableResource(item.dataType!!),
//                    0,
//                    0,
//                    0
//                )
//            }
        }
    }





    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        val inflater = LayoutInflater.from(parent.context)
        return when (viewType) {

            R.layout.single_line_text_custom_field -> {
                val binding = SingleLineTextCustomFieldBinding.inflate(inflater, parent, false)
                TextViewCustomFieldViewHolder(binding , isDisabled)
            }

            R.layout.date_custom_field -> {
                val binding = DateCustomFieldBinding.inflate(inflater, parent, false)
                DateCustomFieldViewHolder(binding, isDisabled)
            }

            R.layout.checkbox_custom_field -> {
                val binding = CheckboxCustomFieldBinding.inflate(inflater, parent, false)
                CheckboxCustomFieldViewHolder(binding, isDisabled)
            }

            R.layout.dropdown_custom_field -> {
                val binding = DropdownCustomFieldBinding.inflate(inflater, parent, false)
                DropdownCustomFieldViewHolder(binding, isDisabled)
            }


            else -> throw IllegalArgumentException("Unknown view type: $viewType")
        }
    }


    override fun getItemViewType(position: Int): Int {
        val item = getItem(position) as Field
        return when (item.dataType) {
            "Text" -> R.layout.single_line_text_custom_field
//            "Number" -> R.layout.number_custom_field
//            "Decimal" -> R.layout.decimal_custom_field
            "Date" -> R.layout.date_custom_field
            "Datetime" -> R.layout.datetime_custom_field
            "Checkbox" -> R.layout.checkbox_custom_field
//            "Auto-Generated Number" -> R.layout.auto_generated_number_custom_field
            "Dropdown" -> R.layout.dropdown_custom_field
//            "Multi-Select" -> R.layout.multi_select_custom_field
//            "Email" -> R.layout.single_line_text_custom_field
//            "URL" -> R.layout.single_line_text_custom_field
//            "Phone" -> R.layout.number_custom_field
//            "Amount" -> R.layout.decimal_custom_field
//            "Percent" -> R.layout.decimal_custom_field
            else -> throw IllegalArgumentException("Unknown item type: ${item.dataType}")
        }
    }


    companion object {
        private val COMPARATOR = object : DiffUtil.ItemCallback<Field>() {
            override fun areItemsTheSame(oldItem: Field, newItem: Field): Boolean =
                oldItem == newItem


            override fun areContentsTheSame(
                oldItem: Field,
                newItem: Field
            ): Boolean =
                oldItem.id == newItem.id
        }
    }

}