package com.example.md3.data.model.checksheet


import com.google.gson.annotations.SerializedName

data class Field(
    @SerializedName("auto_generated_number")
    val autoGeneratedNumber: Any,
    @SerializedName("data_type")
    val dataType: String,
    @SerializedName("dropdown_options")
    val dropdownOptions: DropdownOptions,
    @SerializedName("flag_mandatory")
    val flagMandatory: Boolean,
    @SerializedName("help_text")
    val helpText: String,
    @SerializedName("id")
    val id: String,
    @SerializedName("label_name")
    val labelName: String,
    @SerializedName("value")
    var value: String
)